apiVersion: v1
kind: Service
metadata:
  name: gemlight-service
  namespace: test
spec:
  type: NodePort
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: gemlight
